// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXqmX3bZSlnjEpr0wbA56joM-3sO-dCw',
    appId: '1:937140231077:web:213147573c442ab00de64c',
    messagingSenderId: '937140231077',
    projectId: 'amigo-chat-b5a2d',
    authDomain: 'amigo-chat-b5a2d.firebaseapp.com',
    storageBucket: 'amigo-chat-b5a2d.appspot.com',
    measurementId: 'G-NK7Z1PYRMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEyCIXkd4Z77dRVUQRa1Mr4685ak-UwqE',
    appId: '1:937140231077:android:4e30e9b8cb08487a0de64c',
    messagingSenderId: '937140231077',
    projectId: 'amigo-chat-b5a2d',
    storageBucket: 'amigo-chat-b5a2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOoEn21jos_UZUKJqOtZw2gpqCjzOyxfw',
    appId: '1:937140231077:ios:c98861e783e748cc0de64c',
    messagingSenderId: '937140231077',
    projectId: 'amigo-chat-b5a2d',
    storageBucket: 'amigo-chat-b5a2d.appspot.com',
    iosBundleId: 'com.example.club',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOoEn21jos_UZUKJqOtZw2gpqCjzOyxfw',
    appId: '1:937140231077:ios:b7a67d76d05c773f0de64c',
    messagingSenderId: '937140231077',
    projectId: 'amigo-chat-b5a2d',
    storageBucket: 'amigo-chat-b5a2d.appspot.com',
    iosBundleId: 'com.example.club.RunnerTests',
  );
}
